In [1]:
import numpy as np
import pandas as pd

### 3.인구소멸 위기 지역 top 10
    - 가임기 여성인구수(20-39) / 60세 이상 노령인구
    - 특례시 : 수원 고양, 용인
    - 행정구 : 성남,안산,안양

In [2]:
# 1) 데이터 파일 읽어오기
pail='data/주민등록인구집계현황 (1).csv'
age=pd.read_csv(pail,encoding='euc-kr')
age.head(5)

,연도,월,행정구역구분명,행정구역명,총 인구수,0~9세,10~19세,20~29세,30~39세,40~49세,...,10~19세 (여),20~29세 (여),30~39세 (여),40~49세 (여),50~59세 (여),60~69세 (여),70~79세 (여),80~89세 (여),90~99세 (여),100세 이상 (여)
0,2022,12,도,경기도,13589432,1040954,1327726,1737291,1882300,2284603,...,647283,821150,904073,1121889,1133428,878494,437251,252711,44184,1369
1,2022,12,시군,경기도 가평군,62197,2930,4463,5929,5397,7589,...,2186,2503,2433,3525,5090,6439,3653,2408,411,13
2,2022,12,읍면동,경기도 가평군 가평읍,19555,1020,1673,2094,1795,2630,...,778,937,848,1244,1583,1805,1054,739,126,6
3,2022,12,읍면동,경기도 가평군 북면,3815,108,174,230,223,357,...,93,87,99,154,290,511,294,216,39,1
4,2022,12,읍면동,경기도 가평군 상면,5669,140,259,482,389,533,...,112,151,166,240,515,737,389,244,39,0

In [3]:
age.isna().sum().sum()

0

In [4]:
age.columns,age.values

(Index(['연도', '월', '행정구역구분명', '행정구역명', '총 인구수', '0~9세', '10~19세', '20~29세',
        '30~39세', '40~49세', '50~59세', '60~69세', '70~79세', '80~89세', '90~99세',
        '100세 이상', '총 인구수 (남)', '0~9세 (남)', '10~19세 (남)', '20~29세 (남)',
        '30~39세 (남)', '40~49세 (남)', '50~59세 (남)', '60~69세 (남)', '70~79세 (남)',
        '80~89세 (남)', '90~99세 (남)', '100세 이상 (남)', '총 인구수 (여)', '0~9세 (여)',
        '10~19세 (여)', '20~29세 (여)', '30~39세 (여)', '40~49세 (여)', '50~59세 (여)',
        '60~69세 (여)', '70~79세 (여)', '80~89세 (여)', '90~99세 (여)', '100세 이상 (여)'],
       dtype='object'),
 array([[2022, 12, '도', ..., 252711, 44184, 1369],
        [2022, 12, '시군', ..., 2408, 411, 13],
        [2022, 12, '읍면동', ..., 739, 126, 6],
        ...,
        [2022, 12, '읍면동', ..., 398, 73, 0],
        [2022, 12, '읍면동', ..., 0, 0, 0],
        [2022, 12, '읍면동', ..., 0, 0, 0]], dtype=object))

In [5]:
age.drop(columns=['연도', '월', '행정구역구분명', '총 인구수', '0~9세', '10~19세', '20~29세',
        '30~39세', '40~49세', '50~59세', '총 인구수 (남)', '0~9세 (남)', '10~19세 (남)', '20~29세 (남)',
        '30~39세 (남)', '40~49세 (남)', '50~59세 (남)', '60~69세 (남)', '70~79세 (남)',
        '80~89세 (남)', '90~99세 (남)', '100세 이상 (남)', '총 인구수 (여)', '0~9세 (여)',
        '10~19세 (여)',  '40~49세 (여)', '50~59세 (여)',
        '60~69세 (여)', '70~79세 (여)', '80~89세 (여)', '90~99세 (여)', '100세 이상 (여)'],inplace=True)
age.head(2)

      행정구역명   60~69세  70~79세  80~89세  90~99세  100세 이상  20~29세 (여)  30~39세 (여)
0     경기도    1750962  808663  403721   58065     1725      821150      904073
1  경기도 가평군     13315    7082    3999     564       19        2503        2433

In [6]:
for column in age.columns[1:]:
    age[column] = age[column].astype(int)
age.head(3)

,행정구역명,60~69세,70~79세,80~89세,90~99세,100세 이상,20~29세 (여),30~39세 (여)
0,경기도,1750962,808663,403721,58065,1725,821150,904073
1,경기도 가평군,13315,7082,3999,564,19,2503,2433
2,경기도 가평군 가평읍,3614,1963,1206,163,7,937,848

In [7]:
age['가임기여성인구수'] = age['20~29세 (여)']+age ['30~39세 (여)']
age['60세이상노령인구'] =age['60~69세']+age['70~79세']+age['80~89세']+age['90~99세']+age['100세 이상']
age

,행정구역명,60~69세,70~79세,80~89세,90~99세,100세 이상,20~29세 (여),30~39세 (여),가임기여성인구수,60세이상노령인구
0,경기도,1750962,808663,403721,58065,1725,821150,904073,1725223,3023136
1,경기도 가평군,13315,7082,3999,564,19,2503,2433,4936,24979
2,경기도 가평군 가평읍,3614,1963,1206,163,7,937,848,1785,6953
3,경기도 가평군 북면,1072,578,353,54,1,87,99,186,2058
4,경기도 가평군 상면,1537,788,410,57,0,151,166,317,2792
...,...,...,...,...,...,...,...,...,...,...
615,경기도 화성시 팔탄면,2187,887,566,83,2,296,311,607,3725
616,경기도 화성시 향남읍,7462,3231,1571,211,3,4462,6288,10750,12478
617,경기도 화성시 화산동,3456,1486,646,85,0,1408,1285,2693,5673
618,경기도 화성시동부출장소,0,0,0,0,0,0,0,0,0
619,경기도 화성시동탄출장소,0,0,0,0,0,0,0,0,0

In [8]:
age.columns

Index(['행정구역명', '60~69세', '70~79세', '80~89세', '90~99세', '100세 이상',
       '20~29세 (여)', '30~39세 (여)', '가임기여성인구수', '60세이상노령인구'],
      dtype='object')

In [9]:
age=age[['행정구역명','가임기여성인구수','60세이상노령인구']]
age.head(2)

      행정구역명  가임기여성인구수  60세이상노령인구
0     경기도     1725223    3023136
1  경기도 가평군       4936      24979

In [12]:
age['인구소멸비율'] = (age['가임기여성인구수'] / age['60세이상노령인구']).round(2)
age.head(5)

C:\Users\YONSAI\AppData\Local\Temp\ipykernel_9200\3570511368.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age['인구소멸비율'] = (age['가임기여성인구수'] / age['60세이상노령인구']).round(2)

         행정구역명  가임기여성인구수  60세이상노령인구  인구소멸비율
0        경기도     1725223    3023136    0.57
1     경기도 가평군       4936      24979    0.20
2  경기도 가평군 가평읍      1785       6953    0.26
3   경기도 가평군 북면       186       2058    0.09
4   경기도 가평군 상면       317       2792    0.11